<?php

namespace App\Http\Controllers\finance;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\finance\Invoice;
use App\Models\finance\PaymentRequest;
use App\Models\finance\CreditNote;
use App\Models\finance\Expense;
use App\Models\finance\Pyment;
use App\Models\client\Client;
use App\Services\finance\FinanceService;



class FinanceFunctionController extends Controller
{

    protected $financeService;
    public function __construct(FinanceService $financeService)
    {
        $this->financeService = $financeService;
    }

    public function finance_report(Request $request)
    {
        $type = $request->get('type');
        $data = $this->financeService->getAll($type);

        return view('finance.report.index', [
            'records' => $data['records'],
            'totals' => $data['totals'],
        ]);

    }

    public function invoice_show_pdf($id)
    {
        $finance = Invoice::findOrFail($id);
        $modelItems = $finance->financeItems;
        $model = 'invoice';
        return view('finance.common.show_pdf', compact('finance', 'modelItems', 'model'));
    }

    public function paymentRequest_show_pdf($id)
    {
        $finance = PaymentRequest::findOrFail($id);
        $modelItems = $finance->financeItems;
        $model = 'paymentRequest';
        return view('finance.common.show_pdf', compact('finance', 'modelItems', 'model'));
    }

    public function creditNote_show_pdf($id)
    {
        $finance = CreditNote::findOrFail($id);
        $modelItems = $finance->financeItems;
        $model = 'creditNote';
        return view('finance.common.show_pdf', compact('finance', 'modelItems', 'model'));
    }

    public function expense_show_pdf($id)
    {
        $finance = Expense::findOrFail($id);
        $modelItems = $finance->financeItems;
        $model = 'expense';
        return view('finance.common.show_pdf', compact('finance', 'modelItems', 'model'));
    }

    public function pyment_show_pdf($id)
    {
        $finance = Pyment::findOrFail($id);
        $modelItems = $finance->financeItems;
        $model = 'pyment';
        return view('finance.common.show_pdf', compact('finance', 'modelItems', 'model'));
    }

    public function all_clients_statment()
    {

        $clients = Client::withSum('paymentRequests', 'total')
            ->withSum('pyments', 'total') // Fixed: was 'amount', should be 'total' as per Pyment model
            ->where('status', 'active')
            ->get();
        // this is the attributes names generated by this query paymentRequests_sum_total , pyments_sum_total

        foreach ($clients as $client) {
            $client->neededAmount = $client->paymentRequests_sum_total - $client->pyments_sum_total;
            if ($client->neededAmount > 0)
                $client->creditStatus =  'debtor';
            elseif ($client->neededAmount < 0)
                $client->creditStatus =  'creditor';
            elseif ($client->neededAmount == 0)
                $client->creditStatus =  'balanced';
        }

        return view('clients_statment', compact('clients', '', ''));
    }


}
