<?php

return [

    'junior' => [
        'admin' => [],
        'project' => ['view', 'details'],
        'task' => ['view', 'details'],
        'client' => ['view'],
        'expense' => ['view', 'details', 'create', 'modify'],
        'finance' => [],
        'contract' => [],
        'proposal' => [],
        'lead' => [],
        'request' => ['view', 'details', 'create', 'modify'],
        'hr' => [],
        'calendar' => ['full'],
        'reminder' => ['full'],
        'announcement' => ['view', 'details'],
        'report' => [],
        'support' => [],
        'approve' => [],
        'user' => [],
        'setting' => [],
    ],
    'senior' => [
        'admin' => [],
        'project' => ['view', 'details'],
        'task' => ['view', 'details','create','modify'],
        'client' => ['view'],
        'expense' => ['view', 'details', 'create', 'modify'],
        'finance' => [],
        'contract' => [],
        'proposal' => [],
        'lead' => [],
        'request' => ['view', 'details', 'create', 'modify'],
        'hr' => [],
        'calendar' => ['full'],
        'reminder' => ['full'],
        'announcement' => ['view', 'details'],
        'report' => [],
        'support' => [],
        'approve' => ['full'],
        'user' => [],
        'setting' => [],
    ],
    'manager' => [
        'admin' => [],
        'project' => ['view', 'details','create','modify'],
        'task' => ['view', 'details','create','modify'],
        'client' => ['view'],
        'expense' => ['view', 'details', 'create', 'modify'],
        'finance' => [],
        'contract' => [],
        'proposal' => [],
        'lead' => [],
        'request' => ['view', 'details', 'create', 'modify'],
        'hr' => [],
        'calendar' => ['full'],
        'reminder' => ['full'],
        'announcement' => ['view', 'details'],
        'report' => [],
        'support' => [],
        'approve' => ['full'],
        'user' => [],
        'setting' => [],
    ],
    'hr_manager' => [
        'admin' => [],
        'project' => ['view_global', 'details'],
        'task' => ['view_global', 'details'],
        'client' => ['view_global', 'details'],
        'expense' => ['view_global', 'details'],
        'finance' => ['view_global', 'details'],
        'contract' => ['view_global', 'details'],
        'proposal' => [],
        'lead' => [],
        'request' => ['full'],
        'hr' => ['full'],
        'calendar' => ['full'],
        'reminder' => ['full'],
        'announcement' => ['full'],
        'report' => ['full'],
        'support' => ['view' , 'details'],
        'approve' => ['full'],
        'user' => ['view_global','create','details','modify'],
        'setting' => [],
    ],
    'accountant' => [
        'admin' => [],
        'project' => ['view_global', 'details'],
        'task' => ['view_global', 'details'],
        'client' => ['view_global', 'details'],
        'expense' => ['full'],
        'finance' => ['full'],
        'contract' => ['full'],
        'proposal' => ['full'],
        'lead' => ['full'],
        'request' => ['view_global', 'details', 'create'],
        'hr' => ['view_global'],
        'calendar' => ['full'],
        'reminder' => ['full'],
        'announcement' => ['view', 'details','create'],
        'report' => ['full'],
        'support' => [],
        'approve' => ['full'],
        'user' => ['view' , 'details'],
        'setting' => [],
    ],

];
